// <auto-generated />
namespace HRSmart.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_photo_to_skill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_photo_to_skill));
        
        string IMigrationMetadata.Id
        {
            get { return "201611222229147_added_photo_to_skill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
